name: firebase_parallel_runner
description: Package supports to run flutter tests parallel in different shared on single compile
version: 1.0.0
homepage: https://hirantha.xyz
author: Hirantha Rathnayake
license: MIT
repository: https://github.com/hiranthaR/firebase_parallel_runner.git
funding:
  - https://www.buymeacoffee.com/hiranthar

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

platforms:
  android:

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: xyz.hirantha.firebase_parallel_runner
        pluginClass: FirebaseParallelRunnerPlugin